[ON] Add default bundle
bcgov/aries-oca-bundles pull request #27
Opened 2023-04-19 12:51 UTC by MosCD3

Work on progress to finalize this first bundle contribution

2023-04-19 14:02 UTC, swcurran requested changes
I think the issues raised need to be addressed before merging.

2023-04-19 14:02 UTC, swcurran commented on OCABundles/credentials/ongov-digital-trust/ontario-test-credential/OCABundle.json
> +{
@MosCD3 — the format is not right.  The outer brackets should be square, and what you have for line 2 is not right — the CredDef ID.

2023-04-19 14:02 UTC, swcurran commented on OCABundles/credentials/ongov-digital-trust/ontario-test-credential/OCABundle.json
> +            "capture_base": "EfeQBz5tyC0gett-ETgkg4pkxBwwuQoeYsT-9Nt0cNsc",
This is not the “branding” overlay that we have defined in Aries.  The I’m not sure if “card_overlay” is a OCA overlay or not, but it doesn’t match what is expected by Aries wallets.

2023-05-19 11:14 UTC, swcurran commented on OCABundles/credentials/ongov-digital-trust/ontario-test-credential/OCABundle.json
> +      "attributes": {
The attributes list does not match the attributes in the schema that is identified.  Expecting (based on the schema: 

          "region",
          "issued",
          "street_address",
          "birthdate",
          "family_name",
          "country",
          "postal_code",
          "locality",
          "given_names"

2023-05-19 11:21 UTC, swcurran commented
Sorry for the delay in providing feedback — I’ve been out of the office and travelling.

I notice that you put the bundle in the “credentials” folder but the identifier references a schema object on Sovrin TestNet. As defined and based on instructions in the README, the folder should be in the `schema` folder.  If we don’t change anything, that needs to be moved before merging.

It does raise the question — should there even be a differentiation in folders?  We could make it that there is just one folder that contains the “publisher” of the referenced object.

Any thoughts on that?

2023-11-09 16:15 UTC, amanji commented
Is there any update on this, or can we close until this is ready for PR again?

2023-11-09 17:18 UTC, closed without merging