Schema Validator for OCA Bundles
bcgov/aries-oca-bundles pull request #74
Opened 2023-06-27 17:02 UTC by rajpalc7

2023-06-29 18:24 UTC, amanji requested changes

2023-06-29 18:24 UTC, amanji commented on .github/workflows/static.yml
Why was this file removed?

2023-06-29 18:29 UTC, rajpalc7 commented on .github/workflows/static.yml
@amanji - That file was added in through different branch named validate. I can add the file in this PR if you want

2023-06-29 18:49 UTC, amanji requested changes

2023-06-29 18:49 UTC, amanji commented on .github/workflow/workflows/static.yml
It should still be under `.github/workflows/`

2023-06-29 18:55 UTC, rajpalc7 commented on .github/workflow/workflows/static.yml
fixed now

2023-11-09 16:15 UTC, amanji commented
Is there any update on this, or can we close until the PR is ready for review again?

2023-11-16 17:08 UTC, swcurran commented
@amanji — can you please review. I don’t understand the details.

2023-11-16 17:09 UTC, swcurran commented
BTW — what does “AJV” in the title mean?

2023-11-16 17:12 UTC, closed without merging

2023-11-16 17:14 UTC, amanji commented
> BTW — what does “AJV” in the title mean?

AJV is the JSON validator library used to check that OCA bundles conform to the OCA for Aries specification